// Curated collection of top-rated films (5★, 4.5★, 4★) for the premium slideshow
// These will have TMDB posters fetched automatically

export interface CuratedFilm {
  title: string;
  year: string;
  rating: number;
  genre: string;
  leadActor: string;
  director: string;
}

// 5-STAR FILMS (Masterpieces)
export const FIVE_STAR_FILMS: CuratedFilm[] = [
  { title: "Eternal Sunshine of the Spotless Mind", year: "2004", rating: 5, genre: "Romance, Sci-Fi", leadActor: "Jim Carrey", director: "Michel Gondry" },
  { title: "Up", year: "2009", rating: 5, genre: "Animation, Adventure", leadActor: "Ed Asner", director: "Pete Docter" },
  { title: "Peranbu", year: "2018", rating: 5, genre: "Drama", leadActor: "Mammootty", director: "Ram" },
  { title: "The Shawshank Redemption", year: "1994", rating: 5, genre: "Drama", leadActor: "Tim Robbins", director: "Frank Darabont" },
  { title: "Herbie: Fully Loaded", year: "2005", rating: 5, genre: "Adventure, Comedy", leadActor: "Lindsay Lohan", director: "Angela Robinson" },
  { title: "Sarvam Maya", year: "2025", rating: 5, genre: "Supernatural, Comedy", leadActor: "Nivin Pauly", director: "Akhil Sathyan" },
  { title: "F1", year: "2025", rating: 5, genre: "Sport, Drama", leadActor: "Brad Pitt", director: "Joseph Kosinski" },
];

// 4.5-STAR FILMS (Exceptional)
export const FOUR_HALF_STAR_FILMS: CuratedFilm[] = [
  { title: "Luca", year: "2021", rating: 4.5, genre: "Animation, Adventure", leadActor: "Jacob Tremblay", director: "Enrico Casarosa" },
  { title: "Soul", year: "2020", rating: 4.5, genre: "Animation, Drama", leadActor: "Jamie Foxx", director: "Pete Docter" },
  { title: "Everything Everywhere All at Once", year: "2022", rating: 4.5, genre: "Sci-Fi, Adventure", leadActor: "Michelle Yeoh", director: "Daniels" },
  { title: "Mad Max: Fury Road", year: "2015", rating: 4.5, genre: "Action, Sci-Fi", leadActor: "Tom Hardy", director: "George Miller" },
  { title: "Fight Club", year: "1999", rating: 4.5, genre: "Drama, Thriller", leadActor: "Brad Pitt", director: "David Fincher" },
  { title: "The Dark Knight", year: "2008", rating: 4.5, genre: "Action, Crime", leadActor: "Christian Bale", director: "Christopher Nolan" },
  { title: "Puss in Boots: The Last Wish", year: "2022", rating: 4.5, genre: "Animation, Adventure", leadActor: "Antonio Banderas", director: "Joel Crawford" },
  { title: "The Pursuit of Happyness", year: "2006", rating: 4.5, genre: "Biography, Drama", leadActor: "Will Smith", director: "Gabriele Muccino" },
  { title: "La La Land", year: "2016", rating: 4.5, genre: "Musical, Romance", leadActor: "Ryan Gosling", director: "Damien Chazelle" },
  { title: "Ratatouille", year: "2007", rating: 4.5, genre: "Animation, Comedy", leadActor: "Patton Oswalt", director: "Brad Bird" },
  { title: "Vada Chennai", year: "2018", rating: 4.5, genre: "Crime, Drama", leadActor: "Dhanush", director: "Vetrimaaran" },
  { title: "Viduthalai: Part I", year: "2023", rating: 4.5, genre: "Crime, Drama", leadActor: "Soori", director: "Vetrimaaran" },
  { title: "Aadukalam", year: "2011", rating: 4.5, genre: "Drama, Thriller", leadActor: "Dhanush", director: "Vetrimaaran" },
  { title: "Virumaandi", year: "2004", rating: 4.5, genre: "Action, Drama", leadActor: "Kamal Haasan", director: "Kamal Haasan" },
  { title: "Anbe Sivam", year: "2003", rating: 4.5, genre: "Drama, Comedy", leadActor: "Kamal Haasan", director: "Sundar C." },
  { title: "Pariyerum Perumal", year: "2018", rating: 4.5, genre: "Drama", leadActor: "Kathir", director: "Mari Selvaraj" },
  { title: "Demon Slayer: Mugen Train", year: "2020", rating: 4.5, genre: "Animation, Action", leadActor: "Natsuki Hanae", director: "Haruo Sotozaki" },
  { title: "Taramani", year: "2017", rating: 4.5, genre: "Drama, Romance", leadActor: "Andrea Jeremiah", director: "Ram" },
  { title: "Nimona", year: "2023", rating: 4.5, genre: "Animation, Adventure", leadActor: "Chloë Grace Moretz", director: "Nick Bruno" },
  { title: "Blush", year: "2021", rating: 4.5, genre: "Animation, Short", leadActor: "N/A", director: "Joe Mateo" },
  { title: "Sinners", year: "2025", rating: 4.5, genre: "Horror, Thriller", leadActor: "Michael B. Jordan", director: "Ryan Coogler" },
  { title: "Stranger Things 5: The Finale", year: "2025", rating: 4.5, genre: "Sci-Fi, Horror", leadActor: "Millie Bobby Brown", director: "Duffer Brothers" },
];

// 4-STAR FILMS (Excellent)
export const FOUR_STAR_FILMS: CuratedFilm[] = [
  { title: "Joker", year: "2019", rating: 4, genre: "Crime, Drama", leadActor: "Joaquin Phoenix", director: "Todd Phillips" },
  { title: "Vaazhai", year: "2024", rating: 4, genre: "Drama", leadActor: "Ponvel M.", director: "Mari Selvaraj" },
  { title: "Inside Out", year: "2015", rating: 4, genre: "Animation, Adventure", leadActor: "Amy Poehler", director: "Pete Docter" },
  { title: "Avengers: Infinity War", year: "2018", rating: 4, genre: "Action, Sci-Fi", leadActor: "Robert Downey Jr.", director: "Russo Brothers" },
  { title: "Avengers: Endgame", year: "2019", rating: 4, genre: "Action, Sci-Fi", leadActor: "Robert Downey Jr.", director: "Russo Brothers" },
  { title: "Black Panther", year: "2018", rating: 4, genre: "Action, Sci-Fi", leadActor: "Chadwick Boseman", director: "Ryan Coogler" },
  { title: "Captain America: Civil War", year: "2016", rating: 4, genre: "Action, Sci-Fi", leadActor: "Chris Evans", director: "Russo Brothers" },
  { title: "Captain America: The First Avenger", year: "2011", rating: 4, genre: "Action, Adventure", leadActor: "Chris Evans", director: "Joe Johnston" },
  { title: "Avengers: Age of Ultron", year: "2015", rating: 4, genre: "Action, Sci-Fi", leadActor: "Robert Downey Jr.", director: "Joss Whedon" },
  { title: "Luca", year: "2021", rating: 4, genre: "Animation, Adventure", leadActor: "Jacob Tremblay", director: "Enrico Casarosa" },
  { title: "Spider-Man: Across the Spider-Verse", year: "2023", rating: 4, genre: "Animation, Action", leadActor: "Shameik Moore", director: "Joaquim Dos Santos" },
  { title: "Inception", year: "2010", rating: 4, genre: "Sci-Fi, Action", leadActor: "Leonardo DiCaprio", director: "Christopher Nolan" },
  { title: "Interstellar", year: "2014", rating: 4, genre: "Sci-Fi, Adventure", leadActor: "Matthew McConaughey", director: "Christopher Nolan" },
  { title: "Palm Springs", year: "2020", rating: 4, genre: "Comedy, Sci-Fi", leadActor: "Andy Samberg", director: "Max Barbakow" },
  { title: "About Time", year: "2013", rating: 4, genre: "Romance, Fantasy", leadActor: "Domhnall Gleeson", director: "Richard Curtis" },
  { title: "The Incredible Hulk", year: "2008", rating: 4, genre: "Action, Sci-Fi", leadActor: "Edward Norton", director: "Louis Leterrier" },
  { title: "Moon Knight", year: "2022", rating: 4, genre: "Action, Adventure", leadActor: "Oscar Isaac", director: "Mohamed Diab" },
  { title: "Logan", year: "2017", rating: 4, genre: "Action, Drama", leadActor: "Hugh Jackman", director: "James Mangold" },
  { title: "Sarpatta Parambarai", year: "2021", rating: 4, genre: "Sport, Drama", leadActor: "Arya", director: "Pa. Ranjith" },
  { title: "Jai Bhim", year: "2021", rating: 4, genre: "Legal, Drama", leadActor: "Suriya", director: "T.J. Gnanavel" },
  { title: "Garuda Gamana Vrishabha Vahana", year: "2021", rating: 4, genre: "Crime, Drama", leadActor: "Raj B. Shetty", director: "Raj B. Shetty" },
  { title: "Nayakan", year: "1987", rating: 4, genre: "Crime, Drama", leadActor: "Kamal Haasan", director: "Mani Ratnam" },
  { title: "Thani Oruvan", year: "2015", rating: 4, genre: "Action, Thriller", leadActor: "Jayam Ravi", director: "M. Raja" },
  { title: "Ko", year: "2011", rating: 4, genre: "Political, Thriller", leadActor: "Jiiva", director: "K.V. Anand" },
  { title: "Parasite", year: "2019", rating: 4, genre: "Thriller, Drama", leadActor: "Song Kang-ho", director: "Bong Joon-ho" },
  { title: "Coco", year: "2017", rating: 4, genre: "Animation, Fantasy", leadActor: "Anthony Gonzalez", director: "Lee Unkrich" },
  { title: "Five Feet Apart", year: "2019", rating: 4, genre: "Romance, Drama", leadActor: "Haley Lu Richardson", director: "Justin Baldoni" },
  { title: "Her", year: "2013", rating: 4, genre: "Sci-Fi, Romance", leadActor: "Joaquin Phoenix", director: "Spike Jonze" },
  { title: "Kumbalangi Nights", year: "2019", rating: 4, genre: "Drama, Romance", leadActor: "Fahadh Faasil", director: "Madhu C. Narayanan" },
  { title: "Django Unchained", year: "2012", rating: 4, genre: "Western, Drama", leadActor: "Jamie Foxx", director: "Quentin Tarantino" },
  { title: "WALL·E", year: "2008", rating: 4, genre: "Animation, Sci-Fi", leadActor: "Ben Burtt", director: "Andrew Stanton" },
  { title: "The Super Mario Bros. Movie", year: "2023", rating: 4, genre: "Animation, Adventure", leadActor: "Chris Pratt", director: "Aaron Horvath" },
  { title: "Wreck-It Ralph", year: "2012", rating: 4, genre: "Animation, Comedy", leadActor: "John C. Reilly", director: "Rich Moore" },
  { title: "Ralph Breaks the Internet", year: "2018", rating: 4, genre: "Animation, Adventure", leadActor: "John C. Reilly", director: "Rich Moore" },
  { title: "Big Hero 6", year: "2014", rating: 4, genre: "Animation, Action", leadActor: "Ryan Potter", director: "Don Hall" },
  { title: "Hotel Transylvania", year: "2012", rating: 4, genre: "Animation, Comedy", leadActor: "Adam Sandler", director: "Genndy Tartakovsky" },
  { title: "Goosebumps", year: "2015", rating: 4, genre: "Horror, Comedy", leadActor: "Jack Black", director: "Rob Letterman" },
  { title: "Hey! Sinamika", year: "2022", rating: 4, genre: "Romance, Drama", leadActor: "Dulquer Salmaan", director: "Brinda" },
  { title: "Kadaisi Vivasayi", year: "2021", rating: 4, genre: "Drama", leadActor: "Nallandi", director: "M. Manikandan" },
  { title: "Magamuni", year: "2019", rating: 4, genre: "Crime, Thriller", leadActor: "Arya", director: "Santhakumar" },
  { title: "Ante... Sundaraniki!", year: "2022", rating: 4, genre: "Romance, Comedy", leadActor: "Nani", director: "Vivek Athreya" },
  { title: "Arrival", year: "2016", rating: 4, genre: "Sci-Fi, Drama", leadActor: "Amy Adams", director: "Denis Villeneuve" },
  { title: "Asuran", year: "2019", rating: 4, genre: "Action, Drama", leadActor: "Dhanush", director: "Vetrimaaran" },
  { title: "Onward", year: "2020", rating: 4, genre: "Animation, Adventure", leadActor: "Tom Holland", director: "Dan Scanlon" },
  { title: "Super Deluxe", year: "2019", rating: 4, genre: "Drama, Thriller", leadActor: "Vijay Sethupathi", director: "Thiagarajan Kumararaja" },
  { title: "Kaithi", year: "2019", rating: 4, genre: "Action, Thriller", leadActor: "Karthi", director: "Lokesh Kanagaraj" },
  { title: "PK", year: "2014", rating: 4, genre: "Comedy, Drama", leadActor: "Aamir Khan", director: "Rajkumar Hirani" },
  { title: "Kaathal - The Core", year: "2023", rating: 4, genre: "Drama", leadActor: "Mammootty", director: "Jeo Baby" },
  { title: "Dunkirk", year: "2017", rating: 4, genre: "War, Action", leadActor: "Fionn Whitehead", director: "Christopher Nolan" },
  { title: "Stuart Little", year: "1999", rating: 4, genre: "Family, Comedy", leadActor: "Michael J. Fox", director: "Rob Minkoff" },
  { title: "CODA", year: "2021", rating: 4, genre: "Drama, Music", leadActor: "Emilia Jones", director: "Sian Heder" },
  { title: "The Hangover", year: "2009", rating: 4, genre: "Comedy", leadActor: "Bradley Cooper", director: "Todd Phillips" },
  { title: "The Hangover Part II", year: "2011", rating: 4, genre: "Comedy", leadActor: "Bradley Cooper", director: "Todd Phillips" },
  { title: "The Hangover Part III", year: "2013", rating: 4, genre: "Comedy", leadActor: "Bradley Cooper", director: "Todd Phillips" },
  { title: "Attakathi", year: "2012", rating: 4, genre: "Romance, Comedy", leadActor: "Dinesh", director: "Pa. Ranjith" },
  { title: "Vaagai Sooda Vaa", year: "2011", rating: 4, genre: "Period, Drama", leadActor: "Vimal", director: "A. Sarkunam" },
  { title: "Kumki", year: "2012", rating: 4, genre: "Drama, Romance", leadActor: "Vikram Prabhu", director: "Prabhu Solomon" },
  { title: "Naadodigal", year: "2009", rating: 4, genre: "Drama, Action", leadActor: "Sasikumar", director: "Samuthirakani" },
  { title: "Sathuranga Vettai", year: "2014", rating: 4, genre: "Crime, Comedy", leadActor: "Natarajan Subramaniam", director: "H. Vinoth" },
  { title: "Aruvi", year: "2016", rating: 4, genre: "Drama, Satire", leadActor: "Aditi Balan", director: "Arun Prabhu Purushothaman" },
  { title: "Ratsasan", year: "2018", rating: 4, genre: "Psychological, Thriller", leadActor: "Vishnu Vishal", director: "Ramkumar" },
  { title: "Thadam", year: "2019", rating: 4, genre: "Crime, Thriller", leadActor: "Arun Vijay", director: "Magizh Thirumeni" },
  { title: "Visaranai", year: "2015", rating: 4, genre: "Crime, Drama", leadActor: "Dinesh", director: "Vetrimaaran" },
  { title: "Meaghamann", year: "2014", rating: 4, genre: "Action, Thriller", leadActor: "Arya", director: "Magizh Thirumeni" },
  { title: "Deiva Thirumagal", year: "2011", rating: 4, genre: "Drama", leadActor: "Vikram", director: "A.L. Vijay" },
  { title: "Mankatha", year: "2011", rating: 4, genre: "Action, Crime", leadActor: "Ajith Kumar", director: "Venkat Prabhu" },
  { title: "Atrangi Re", year: "2021", rating: 4, genre: "Romance, Drama", leadActor: "Dhanush", director: "Aanand L. Rai" },
  { title: "96", year: "2018", rating: 4, genre: "Romance, Drama", leadActor: "Vijay Sethupathi", director: "C. Prem Kumar" },
  { title: "Vasool Raja MBBS", year: "2004", rating: 4, genre: "Comedy, Drama", leadActor: "Kamal Haasan", director: "Saran" },
  { title: "Varuthapadatha Valibar Sangam", year: "2013", rating: 4, genre: "Comedy", leadActor: "Sivakarthikeyan", director: "Ponram" },
  { title: "Siva Manasula Sakthi", year: "2009", rating: 4, genre: "Comedy, Romance", leadActor: "Jiiva", director: "M. Rajesh" },
  { title: "Oru Kal Oru Kannadi", year: "2012", rating: 4, genre: "Comedy", leadActor: "Udhayanidhi Stalin", director: "M. Rajesh" },
  { title: "Something Something… Unakkum Enakkum", year: "2006", rating: 4, genre: "Romance, Comedy", leadActor: "Jayam Ravi", director: "M. Raja" },
  { title: "Idharkuthane Aasaipattai Balakumara", year: "2013", rating: 4, genre: "Comedy", leadActor: "Vijay Sethupathi", director: "Gokul" },
  { title: "Meyaadha Maan", year: "2017", rating: 4, genre: "Romance, Comedy", leadActor: "Vaibhav", director: "Rathna Kumar" },
  { title: "Dharmadurai", year: "2016", rating: 4, genre: "Drama", leadActor: "Vijay Sethupathi", director: "Seenu Ramasamy" },
  { title: "Uttama Villain", year: "2015", rating: 4, genre: "Comedy, Drama", leadActor: "Kamal Haasan", director: "Ramesh Aravind" },
  { title: "Raavanan", year: "2010", rating: 4, genre: "Action, Adventure", leadActor: "Vikram", director: "Mani Ratnam" },
  { title: "Aayirathil Oruvan", year: "2010", rating: 4, genre: "Adventure, Fantasy", leadActor: "Karthi", director: "Selvaraghavan" },
  { title: "Madras", year: "2014", rating: 4, genre: "Action, Drama", leadActor: "Karthi", director: "Pa. Ranjith" },
  { title: "Velaiyilla Pattathari", year: "2014", rating: 4, genre: "Drama, Comedy", leadActor: "Dhanush", director: "Velraj" },
  { title: "Dasavatharam", year: "2008", rating: 4, genre: "Sci-Fi, Action", leadActor: "Kamal Haasan", director: "K.S. Ravikumar" },
  { title: "Mudhalvan", year: "1999", rating: 4, genre: "Political, Thriller", leadActor: "Arjun Sarja", director: "S. Shankar" },
  { title: "Pudhupettai", year: "2006", rating: 4, genre: "Crime, Drama", leadActor: "Dhanush", director: "Selvaraghavan" },
  { title: "3", year: "2012", rating: 4, genre: "Romance, Thriller", leadActor: "Dhanush", director: "Aishwarya R. Dhanush" },
  { title: "Kadhal Konden", year: "2003", rating: 4, genre: "Romance, Thriller", leadActor: "Dhanush", director: "Selvaraghavan" },
  { title: "Padayappa", year: "1999", rating: 4, genre: "Action, Drama", leadActor: "Rajinikanth", director: "K.S. Ravikumar" },
  { title: "Muthu", year: "1995", rating: 4, genre: "Drama, Romance", leadActor: "Rajinikanth", director: "K.S. Ravikumar" },
  { title: "Annamalai", year: "1992", rating: 4, genre: "Action, Drama", leadActor: "Rajinikanth", director: "Suresh Krissna" },
  { title: "Baasha", year: "1995", rating: 4, genre: "Action, Crime", leadActor: "Rajinikanth", director: "Suresh Krissna" },
  { title: "Chandramukhi", year: "2005", rating: 4, genre: "Horror, Comedy", leadActor: "Rajinikanth", director: "P. Vasu" },
  { title: "Kabali", year: "2016", rating: 4, genre: "Action, Crime", leadActor: "Rajinikanth", director: "Pa. Ranjith" },
  { title: "Now You See Me", year: "2013", rating: 4, genre: "Thriller, Crime", leadActor: "Jesse Eisenberg", director: "Louis Leterrier" },
  { title: "Premam", year: "2015", rating: 4, genre: "Romance, Drama", leadActor: "Nivin Pauly", director: "Alphonse Puthren" },
  { title: "Shaolin Soccer", year: "2001", rating: 4, genre: "Action, Comedy", leadActor: "Stephen Chow", director: "Stephen Chow" },
  { title: "Kung Fu Hustle", year: "2004", rating: 4, genre: "Action, Comedy", leadActor: "Stephen Chow", director: "Stephen Chow" },
  { title: "Dangal", year: "2016", rating: 4, genre: "Sport, Biography", leadActor: "Aamir Khan", director: "Nitesh Tiwari" },
  { title: "M.S. Dhoni: The Untold Story", year: "2016", rating: 4, genre: "Biography, Sport", leadActor: "Sushant Singh Rajput", director: "Neeraj Pandey" },
  { title: "Paava Kadhaigal", year: "2020", rating: 4, genre: "Anthology, Drama", leadActor: "Various", director: "Vetri Maaran" },
  { title: "Arundhati", year: "2009", rating: 4, genre: "Horror, Fantasy", leadActor: "Anushka Shetty", director: "Kodi Ramakrishna" },
  { title: "Yavanum Nalam", year: "2009", rating: 4, genre: "Horror, Thriller", leadActor: "Madhavan", director: "Vikram Kumar" },
  { title: "Jersey", year: "2019", rating: 4, genre: "Sport, Drama", leadActor: "Nani", director: "Gowtam Tinnanuri" },
  { title: "Nani's Gang Leader", year: "2019", rating: 4, genre: "Crime, Comedy", leadActor: "Nani", director: "Vikram K. Kumar" },
  { title: "John Wick", year: "2014", rating: 4, genre: "Action, Thriller", leadActor: "Keanu Reeves", director: "Chad Stahelski" },
  { title: "Ghilli", year: "2004", rating: 4, genre: "Action, Sport", leadActor: "Vijay", director: "Dharani" },
  { title: "Thuppakki", year: "2012", rating: 4, genre: "Action, Thriller", leadActor: "Vijay", director: "AR Murugadoss" },
  { title: "Kaththi", year: "2014", rating: 4, genre: "Action, Drama", leadActor: "Vijay", director: "AR Murugadoss" },
  { title: "Pokkiri", year: "2007", rating: 4, genre: "Action, Thriller", leadActor: "Vijay", director: "Prabhu Deva" },
  { title: "Sachein", year: "2005", rating: 4, genre: "Romance, Comedy", leadActor: "Vijay", director: "John Mahendran" },
  { title: "Kushi", year: "2000", rating: 4, genre: "Romance, Comedy", leadActor: "Vijay", director: "S.J. Suryah" },
  { title: "Friends", year: "2001", rating: 4, genre: "Comedy, Drama", leadActor: "Vijay", director: "Siddique" },
  { title: "Kadhalukku Mariyaadai", year: "1997", rating: 4, genre: "Romance, Drama", leadActor: "Vijay", director: "Fazil" },
  { title: "Poove Unakkaga", year: "1996", rating: 4, genre: "Romance, Drama", leadActor: "Vijay", director: "Vikraman" },
  { title: "Ayan", year: "2009", rating: 4, genre: "Action, Thriller", leadActor: "Suriya", director: "K.V. Anand" },
  { title: "Singam", year: "2010", rating: 4, genre: "Action, Masala", leadActor: "Suriya", director: "Hari" },
  { title: "Soorarai Pottru", year: "2020", rating: 4, genre: "Drama", leadActor: "Suriya", director: "Sudha Kongara" },
  { title: "Source Code", year: "2011", rating: 4, genre: "Sci-Fi, Thriller", leadActor: "Jake Gyllenhaal", director: "Duncan Jones" },
  { title: "The Rat", year: "2016", rating: 4, genre: "Documentary", leadActor: "N/A", director: "Theo Anthony" },
  { title: "Sivakasi", year: "2005", rating: 4, genre: "Action, Masala", leadActor: "Vijay", director: "Perarasu" },
  { title: "12th Fail", year: "2023", rating: 4, genre: "Biography, Drama", leadActor: "Vikrant Massey", director: "Vidhu Vinod Chopra" },
  { title: "Tumbbad", year: "2018", rating: 4, genre: "Horror, Fantasy", leadActor: "Sohum Shah", director: "Rahi Anil Barve" },
  { title: "Turbo", year: "2013", rating: 4, genre: "Animation, Sport", leadActor: "Ryan Reynolds", director: "David Soren" },
  { title: "Laal Singh Chaddha", year: "2022", rating: 4, genre: "Drama, Romance", leadActor: "Aamir Khan", director: "Advait Chandan" },
  { title: "Squid Game", year: "2021", rating: 4, genre: "Thriller, Drama", leadActor: "Lee Jung-jae", director: "Hwang Dong-hyuk" },
  { title: "The Penguin", year: "2024", rating: 4, genre: "Crime, Drama", leadActor: "Colin Farrell", director: "Various" },
  { title: "Adolescence", year: "2025", rating: 4, genre: "Crime, Drama", leadActor: "Stephen Graham", director: "Philip Barantini" },
  { title: "Ponman", year: "2025", rating: 4, genre: "Black Comedy, Thriller", leadActor: "Basil Joseph", director: "Jothish Shankar" },
  { title: "Veera Dheera Sooran: Part 2", year: "2025", rating: 4, genre: "Action, Thriller", leadActor: "Vikram", director: "S.U. Arun Kumar" },
  { title: "Thunderbolts*", year: "2025", rating: 4, genre: "Action, Sci-Fi", leadActor: "Florence Pugh", director: "Jake Schreier" },
  { title: "Tourist Family", year: "2025", rating: 4, genre: "Comedy, Drama", leadActor: "N/A", director: "N/A" },
  { title: "A Minecraft Movie", year: "2025", rating: 4, genre: "Adventure, Fantasy", leadActor: "Jason Momoa", director: "Jared Hess" },
  { title: "Money Heist: From Tokyo to Berlin", year: "2021", rating: 4, genre: "Documentary", leadActor: "Úrsula Corberó", director: "Luis Alfaro" },
  { title: "The Wild Robot", year: "2024", rating: 4, genre: "Animation, Adventure", leadActor: "Lupita Nyong'o", director: "Chris Sanders" },
  { title: "Ford v Ferrari", year: "2019", rating: 4, genre: "Sport, Drama", leadActor: "Christian Bale", director: "James Mangold" },
  { title: "Superman", year: "2025", rating: 4, genre: "Action, Sci-Fi", leadActor: "David Corenswet", director: "James Gunn" },
  { title: "The Dark Knight Rises", year: "2012", rating: 4, genre: "Action, Thriller", leadActor: "Christian Bale", director: "Christopher Nolan" },
  { title: "Batman Begins", year: "2005", rating: 4, genre: "Action, Thriller", leadActor: "Christian Bale", director: "Christopher Nolan" },
  { title: "Parandhu Po", year: "2025", rating: 4, genre: "Drama", leadActor: "Grace Antony", director: "Ram" },
  { title: "The Fantastic Four: First Steps", year: "2025", rating: 4, genre: "Action, Sci-Fi", leadActor: "Pedro Pascal", director: "Matt Shakman" },
  { title: "Demon Slayer: Kimetsu no Yaiba", year: "2019", rating: 4, genre: "Animation, Action", leadActor: "Natsuki Hanae", director: "Haruo Sotozaki" },
  { title: "Demon Slayer: Sibling's Bond", year: "2019", rating: 4, genre: "Animation, Action", leadActor: "Natsuki Hanae", director: "Haruo Sotozaki" },
  { title: "Su from So", year: "2025", rating: 4, genre: "Comedy, Drama", leadActor: "Raj B. Shetty", director: "J. P. Thuminad" },
  { title: "Thulladha Manamum Thullum", year: "1999", rating: 4, genre: "Romance, Drama", leadActor: "Vijay", director: "Ezhil" },
  { title: "Bison Kaalamaadan", year: "2025", rating: 4, genre: "Sport, Drama", leadActor: "Dhruv Vikram", director: "Mari Selvaraj" },
  { title: "Aavesham", year: "2024", rating: 4, genre: "Action, Comedy", leadActor: "Fahadh Faasil", director: "Jithu Madhavan" },
  { title: "The Bad Guys 2", year: "2025", rating: 4, genre: "Animation, Comedy", leadActor: "Sam Rockwell", director: "Pierre Perifel" },
  { title: "A Real Pain", year: "2024", rating: 4, genre: "Comedy, Drama", leadActor: "Jesse Eisenberg", director: "Jesse Eisenberg" },
  { title: "Flow", year: "2024", rating: 4, genre: "Animation, Adventure", leadActor: "N/A", director: "Gints Zilbalodis" },
  { title: "Wake Up Dead Man: A Knives Out Mystery", year: "2025", rating: 4, genre: "Mystery, Crime", leadActor: "Daniel Craig", director: "Rian Johnson" },
  { title: "Avatar: Fire and Ash", year: "2025", rating: 4, genre: "Sci-Fi, Adventure", leadActor: "Sam Worthington", director: "James Cameron" },
  { title: "Kaantha", year: "2025", rating: 4, genre: "Drama", leadActor: "Dulquer Salmaan", director: "Selvamani Selvaraj" },
  { title: "Frankenstein", year: "2025", rating: 4, genre: "Horror, Sci-Fi", leadActor: "Jacob Elordi", director: "Guillermo del Toro" },
  { title: "Zootopia 2", year: "2025", rating: 4, genre: "Animation, Adventure", leadActor: "Ginnifer Goodwin", director: "Byron Howard" },
];

// Combined top-rated films for slideshow
export const TOP_RATED_FILMS: CuratedFilm[] = [
  ...FIVE_STAR_FILMS,
  ...FOUR_HALF_STAR_FILMS,
  ...FOUR_STAR_FILMS
];
